name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cuda
      env:
        cuda: "11.3"
      run: chmod +x ./install_cuda.sh;./install_cuda.sh
      shell: bash
       
    - name: make
      run: make
